# Generated by Django 6.1 on 2026-08-16 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_product_contact_number_product_whatsapp_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('kg', 'per KG'), ('gram', 'per Gram'), ('quintal', 'per Quintal'), ('ton', 'per Ton'), ('piece', 'per Piece'), ('pack', 'per Pack')], default='kg', max_length=20),
        ),
    ]
