# Generated by Django 6.1 on 2026-08-17 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_product_farmer_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='seller_name',
            field=models.CharField(blank=True, help_text='Custom name for the seller/farmer', max_length=150, null=True),
        ),
    ]
