# Generated by Django 6.1 on 2026-08-17 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_product_seller_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='soil_report_pdf',
        ),
        migrations.AddField(
            model_name='profile',
            name='helpful_website_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='helpful_website_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
